package com.aries.storyreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.aries.storyreader.bean.User;
import com.aries.storyreader.bean.Dub;
import com.aries.storyreader.bean.Node;

import com.aries.storyreader.dao.UserDao;
import com.aries.storyreader.dao.DubDao;
import com.aries.storyreader.dao.NodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig dubDaoConfig;
    private final DaoConfig nodeDaoConfig;

    private final UserDao userDao;
    private final DubDao dubDao;
    private final NodeDao nodeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dubDaoConfig = daoConfigMap.get(DubDao.class).clone();
        dubDaoConfig.initIdentityScope(type);

        nodeDaoConfig = daoConfigMap.get(NodeDao.class).clone();
        nodeDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        dubDao = new DubDao(dubDaoConfig, this);
        nodeDao = new NodeDao(nodeDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Dub.class, dubDao);
        registerDao(Node.class, nodeDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        dubDaoConfig.getIdentityScope().clear();
        nodeDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DubDao getDubDao() {
        return dubDao;
    }

    public NodeDao getNodeDao() {
        return nodeDao;
    }

}
