package com.aries.storyreader.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String portrait;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, String portrait) {
        this.id = id;
        this.name = name;
        this.portrait = portrait;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPortrait() {
        return portrait;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

}
